# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Lab1Tumblr' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lab1Tumblr
  pod 'AFNetworking', '~> 2.6'
end
